name: Update

on:
  workflow_dispatch:
  push:
    branches: [main]
  schedule:
    - cron: "5 */4 * * *"

env:
  # Disable incremental compilation for faster from-scratch builds
  CARGO_INCREMENTAL: 0

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2

      - name: rustup
        run: rustup update

      - name: build
        run: cargo build --release

      - name: Update
        run: ./target/release/fanatics update urls.csv > prices.csv

      - name: Readme
        run: ./target/release/fanatics readme prices.csv > README.md

      - name: commit
        run: |
          timestamp=$(date -u)
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          git commit -m "Updated: ${timestamp}" || exit 0
          git push
